package com.tools.entites;

// Generated 7 Sep, 2017 11:17:32 AM by Hibernate Tools 4.0.0

/**
 * Advisor generated by hbm2java
 */
public class Advisor implements java.io.Serializable {

	private int advisorNo;
	private String firstNm;
	private String lastNm;
	private String qualification;
	private int experience;
	private int contactNo;
	private String emailAddress;

	public Advisor() {
	}

	public int getAdvisorNo() {
		return this.advisorNo;
	}

	public void setAdvisorNo(int advisorNo) {
		this.advisorNo = advisorNo;
	}

	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	public int getExperience() {
		return this.experience;
	}

	public void setExperience(int experience) {
		this.experience = experience;
	}

	public int getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(int contactNo) {
		this.contactNo = contactNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

}
